import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";
import { app_utils } from "@/utils";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  // const { data, isLoading } = api.example.hello.useQuery({ text: "from tRPC" });
  const { getRandomPokemon } = app_utils;
  const [first_id, setFirstId] = useState(0);
  const [second_id, setSecondId] = useState(0);

  useEffect(() => {
    setFirstId(getRandomPokemon());
    setSecondId(getRandomPokemon(first_id));
  }, []);

  return (
    <>
      <Head>
        <title>roundest</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen w-screen flex-col items-center justify-center">
        <div className="text-center text-2xl">Which Pokemon is Rounder?</div>

        <div className="p-2" />

        <div className="flex max-w-2xl items-center justify-between rounded border p-8 ">
          <div className="h-16 w-16  bg-red-200">
            {first_id ? first_id : ""}
          </div>
          <div className="p-8">Vs</div>
          <div className="h-16 w-16 bg-red-200">
            {second_id ? second_id : ""}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
